spring:
  datasource:
    username: "root"
    password: "cksh20000817"
    url: jdbc:mysql://localhost:3306/property_pro_ms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2GB
mybatis:
  type-aliases-package: com.lclgl.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true